 {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "Prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://10.29.0.1:9090",
                "version": 1
            }
            # ,
            # {
            #    "access":"proxy",
            #     "editable": true,
            #     "name": "VictoriaMetric",
            #     "orgId": 1,
            #     "type": "prometheus",
            #     "url": "http://victoria-service.monitoring.svc:8428",
            #     "version": 1
            # }
        ]
    }